### ISSUE TITLE
Could you upload dataset that include the noisy images?

### ISSUE THREAD

**Issue by YifeiAI** [Vandermode/ELD#12]
Hi,

Great work! Congratulations. I downloaded your ELD dataset but it doesn't contain the images processed by your noisy model. Is it possible to also upload the noisy images? 

Thanks.

**Comment by Vandermode** [comment]
Hi, what's kind of dataset you want? a synthetic noisy dataset based upon SID dataset?

**Comment by YifeiAI** [comment]
> Hi, what's kind of dataset you want? a synthetic noisy dataset based upon SID dataset?

Hi, thanks for your reply.  Yes I meant synthetic noisy SID dataset. Is it possible to share this noisy dataset? (or any synthetic noisy dataset could be used for training). Thanks in advance!

**Comment by Vandermode** [comment]
Ok, I could generate four synthetic datasets which are corresponding to four different devices (Sony, Nikon and Canon) used in our work.  Please wait for some days, as the datasets are very large.

**Comment by YifeiAI** [comment]
Hi, that would be great! Thank you very much.

**Comment by zhongyi-zhou** [comment]
@Vandermode Hi! Can I also have this synthetic dataset for training?

**Comment by Vandermode** [comment]
@JoeyChuuichi Hi I see your email but cannot reply to you because my BIT email is no longer activated. Please reach me at my new email address kxwei at princeton.edu. As for your request, I'm preparing and uploading the synthetic datasets, and you would see them in next few days:)

**Comment by zhongyi-zhou** [comment]
@Vandermode 
Thank you so much!

**Comment by Vandermode** [comment]
@JoeyChuuichi done:) please check updates

**Comment by zhongyi-zhou** [comment]
@Vandermode Cool! Thank you!

**Comment by zhongyi-zhou** [comment]
@Vandermode Hi! I would like to ask for some details on installing your customized rawpy library as is described here.


> **Notice this codebase relies on my own customized rawpy, which provides more functionalities than the official one.** 
> This is released together with our datasets and the pretrained models. To build rawpy from source, please first compile and install the LibRaw library following the official instructions, then type pip install -e . in the rawpy directory.

I have installed the official libraw and I am not quite sure where is "the rawpy directory" mentioned above. Do you mean the official repo [here](https://github.com/letmaik/rawpy)? I am not quite familiar with building these packages from source but it seems that if we build all packages from official source codes, we still cannot install your "customized" functionalities. When running `util/lmdb_data.py`, the following error appears on my side (which I believe refers to one of the customized functions):
```
AttributeError: 'rawpy._rawpy.RawPy' object has no attribute 'rgb_camera_matrix'
```

**Comment by Vandermode** [comment]
@JoeyChuuichi I uploaded the customized version in the Google drive / Baidudisk (See readme).

**Comment by zhongyi-zhou** [comment]
@Vandermode Hi! Thanks for the updates and I found there are lots of useful functions in this new rawpy library!

I recently found another bug here:
https://github.com/Vandermode/ELD/blob/f5cd9cdb2f05e96760f09ed3d8516b25fb1b3b26/train_syn.py#L50-L53

I think it refers to a customized .db file but I cannot find it in the google drive you shared. From my understanding, the .db files in google drive should be the ones used in the following codes:

https://github.com/Vandermode/ELD/blob/f5cd9cdb2f05e96760f09ed3d8516b25fb1b3b26/train_syn.py#L66-L70

Could you help update the google drive and include the ```'SID_Sony_Raw.db'``` file/folder?

Also, I guess this folder may be quite relevant to the original SID dataset (i.e., "real pairs" in your paper). If it can make the thing convenient for you, you can release a code instructing us how to create this ```'SID_Sony_Raw.db'``` based on the SID-SONY dataset we have in our local computer.

**Comment by Vandermode** [comment]
Hi @JoeyChuuichi , Thanks for your encouraging feedback! As for your question, the "SID_Sony_Raw" is just the clean target dataset like "SID_Sony_target_Raw" (the difference is all the repeated scenes are filtered out). 
Please refer to https://github.com/Vandermode/ELD/blob/f5cd9cdb2f05e96760f09ed3d8516b25fb1b3b26/util/lmdb_data.py#L232 for more details.

**Comment by wanglixilinx** [comment]
> @Vandermode Hi! I would like to ask for some details on installing your customized rawpy library as is described here.
> 
> > **Notice this codebase relies on my own customized rawpy, which provides more functionalities than the official one.**
> > This is released together with our datasets and the pretrained models. To build rawpy from source, please first compile and install the LibRaw library following the official instructions, then type pip install -e . in the rawpy directory.
> 
> I have installed the official libraw and I am not quite sure where is "the rawpy directory" mentioned above. Do you mean the official repo [here](https://github.com/letmaik/rawpy)? I am not quite familiar with building these packages from source but it seems that if we build all packages from official source codes, we still cannot install your "customized" functionalities. When running `util/lmdb_data.py`, the following error appears on my side (which I believe refers to one of the customized functions):
> 
> ```
> AttributeError: 'rawpy._rawpy.RawPy' object has no attribute 'rgb_camera_matrix'
> ```

Hi, @zhongyi-zhou, how do you solve this problem?

**Comment by zhongyi-zhou** [comment]
@wanglixilinx 
I think the authors have addressed this issue here:

> @JoeyChuuichi I uploaded the customized version in the Google drive / Baidudisk (See readme).

Simply following their official instruction [[here]](https://github.com/Vandermode/ELD#prerequisites) should work.

**Comment by wanglixilinx** [comment]
@zhongyi-zhou ， thanks for your reply. I have followed the official instruction and solved the problem.
