### ISSUE TITLE
where do you multify the luma ratio ?

### ISSUE THREAD

**Issue by oneTaken** [Vandermode/ELD#14]
In you dataset description, the reference frame with a proper exposure time, and have a f in [100, 200] to decrease exposure time to simulate low light situation.   
But I do not find where to multify the f in your paper, because it's obviously have luma difference in the raw pair.

**Comment by Vandermode** [comment]
multify -> multiply?

We multiply the ratio just like what the SID [1] did.

[1] Learning to see in the dark

**Comment by oneTaken** [comment]
Thx.
