### ISSUE TITLE
Noise generation 

### ISSUE THREAD

**Issue by ducha-aiki** [Vandermode/ELD#18]
Hi,

Thank you for the cool paper! Are you going to release also functions for the generating synthetic noise described in the paper?

**Comment by Vandermode** [comment]
Hi, thanks for your interest:) Currently, the noise model (and the calibration method) would not be released as they have been involved in the commercial project. I could provide the synthetic datasets, but this may not fulfill the objective you in your mentioned issue.

**Comment by Vandermode** [comment]
Hi, thanks for your interest:) Currently, the noise model (and the calibration method) would not be released as they have been involved in the commercial project. I could provide the synthetic datasets, but this may not fulfill the objective you in your mentioned issue.

**Comment by ducha-aiki** [comment]
Unfortunately for us, but I fully understand :) Good luck for your commercial product!
