### ISSUE TITLE
What's the effect of IlluminanceCorrect?

### ISSUE THREAD

**Issue by YouCaiJun98** [Vandermode/ELD#19]
Hello and thanks for your amazing job!
I got quite confused about the effect of IlluminanceCorrect func at https://github.com/Vandermode/ELD/blob/aa0edb44a8fc20e01f83c1f6e93ee70d3190e142/models/ELD_model.py#L139
It seems like some kind of normalization, yet I didn't figure out why it should be applied here, could you please explain it for me? Thanks a lot :)

**Comment by Vandermode** [comment]
Hi, thanks for your interest.  ```IlluminanceCorrect``` in fact performs a function as stated in the paper: ```To account for the imprecisions of shutter speed and analog gain [2], a single scalar is calculated and multiplied into the reconstructed image to minimize the mean square error evaluated by the ground truth```.

**Comment by YouCaiJun98** [comment]
I see, thanks for your answer! 👍
