### ISSUE TITLE
Training Settings of Paired-SID Baseline

### ISSUE THREAD

**Issue by YouCaiJun98** [Vandermode/ELD#20]
Hello and sorry for bothering u again :stuck_out_tongue_winking_eye:
I'm trying to reproduce the Paired-SID baseline according to the training settings from your paper:
```  
Our implementation is based on PyTorch. We train the models with 200 epoch using L1 loss and Adam optimizer with 
batch size 1. The learning rate is initially set to 10−4, then halved at epoch 100, and finally reduced to 10−5 
at epoch 180.
```  
I tested the checkpoint you provided and it achieved 38.87dB on SID-Sony(Raw), while the model trained by myself can only acquire around 36.80dB under the same test settings. I launched another experiment with a larger batch size(16), longer training procedure(about 600 epochs) and more coarse-to-fine lr settings(1e-3 to 1e-6) and ended up with a model which is still worse than the baseline(~0.4dB lower). 
I wonder if I missed any important settings, if possible, could you please share your training settings with me?  Thanks a lot! 😄

**Comment by Vandermode** [comment]
Hi, I'm uploading several synthetic datasets together with a training script to reproduce our pretrained models. Please wait 2-3 days to see these updates.

**Comment by YouCaiJun98** [comment]
COOL! Quite Looking Forward to It! :laughing:

**Comment by Vandermode** [comment]
done:) please check updates

**Comment by YouCaiJun98** [comment]
Great! Thanks for your time！😄

**Comment by YouCaiJun98** [comment]
Cool! With your training script, I acquired a sid-paired baseline with 39.16dB, thanks for your help! 😺
