### ISSUE TITLE
The number and order of images in the scene-5 of ELD.7z are wrong 

### ISSUE THREAD

**Issue by fenghansen** [Vandermode/ELD#21]
There are 18 raw images in the SonyA7S2 sub-dataset and 17 raw images in the Canon700D sub-dataset.
Since the verification code you released selects the picture based on the number, this error will cause the data to be mismatched, and then the wrong verification result will be obtained.
Specifically, since GT is corresponding to a very dark image, the corrector will align the brightness to black, resulting in the PSNR being pulled up to about 70dB.
I hope you can update ELD.7z and explain which version of the data should be used as a benchmark for future works to compare.

**Comment by Vandermode** [comment]
Hi, Thanks for pointing this out. It looks like I mistakenly uploaded an unfinished version of the ELD dataset and thus it has some files not filtered out. I have uploaded my local version of the ELD dataset, which is used for evaluation as our paper.
