### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by tongchangD** [Vandermode/ELD#22]
Have you tried any other loss functions？
My output is not converging between zero and one

**Comment by Vandermode** [comment]
Yes you can, but L1 loss is good enough to achieve reasonable result

**Comment by tongchangD** [comment]
But the output of my model is not normalized from 0 to 1, especially for the reflective position.

但是我的模型始终无法将输出归一化到0与1之间，尤其是反光区域，超过1太多

**Comment by Vandermode** [comment]
Since loss functions are out of focus in this research project, we simply tried L1 loss following SID paper.
Performing 0-1 clipping in the end may be helpful

**Comment by tongchangD** [comment]
thanks
