### ISSUE TITLE
SID_Sony_Raw.db missing

### ISSUE THREAD

**Issue by sheyuwei** [Vandermode/ELD#29]
HI，when i tested vis_data.py, SID_Sony_Raw.db was missing.Google Drive don't have this file.

**Comment by Vandermode** [comment]
Hi, please generate the dataset yourself according to [util/lmdb_data.py](https://github.com/Vandermode/ELD/blob/f5cd9cdb2f05e96760f09ed3d8516b25fb1b3b26/util/lmdb_data.py)
