### ISSUE TITLE
code release question

### ISSUE THREAD

**Issue by oneTaken** [Vandermode/ELD#3]
Hi, nice work for your paper.

It's very helpful to know more about your idea with the code.

When will you release the code ?

**Comment by Vandermode** [comment]
I'm preparing an extension of this work, it's nearly done. Once finished, I'll clean and release my code

**Comment by oneTaken** [comment]
Sounds exciting.

I'll follow your extension work and the code.

**Comment by JackChenZZ** [comment]
Hi, nice work for your paper.
I want to how to add the photon shot noise? That is, how to obtain the Np?

**Comment by Vandermode** [comment]
@DML-source 
you need to have system overall gain K to convert your digital number D to the number of photoelectrons I via I = D / K.  Then you impose a  Poisson distribution on I, and finally revert it by D* = I* x K.

and Np = D* - D (though you don't need to explicitly calculate Np as you already have D*)

**Comment by JackChenZZ** [comment]
> @DML-source
> you need to have system overall gain K to convert your digital number D to the number of photoelectrons I via I = D / K. Then you impose a Poisson distribution on I, and finally revert it by D* = I* x K.
> 
> and Np = D* - D (though you don't need to explicitly calculate Np as you already have D*)

Thanks for your explanation. 
So, is the param for Poisson distribution fixed, or how to choose this param?

**Comment by Vandermode** [comment]
@DML-source  there is no param for Poisson distribution.

The only param to control the photon shot noise is the system overall gain K

**Comment by JackChenZZ** [comment]
> @DML-source there is no param for Poisson distribution.
> 
> The only param to control the photon shot noise is the system overall gain K

I am sorry, but the Poisson distribution needs the param lamda, right?  I am confused about how to obtain the I* from I.

**Comment by Vandermode** [comment]
Actually, you should feed I* to lam

**Comment by dawnlh** [comment]
nice work! looking forward to the codes 👀
