### ISSUE TITLE
Relationship between "K" and ISO

### ISSUE THREAD

**Issue by wyf0912** [Vandermode/ELD#30]
Thanks for sharing the code of the great works!

Since I do not have exactly the same devices as the paper,
could you share the ISO corresponding to the minimum and maximum of ”K"?

Thanks a lot

**Comment by Vandermode** [comment]
Hi, Thanks for your interest.
for the question, "Kmin" -> ISO 100, "Kmax" -> ISO 6400

**Comment by wyf0912** [comment]
> Hi, Thanks for your interest. for the question, "Kmin" -> ISO 100, "Kmax" -> ISO 6400

Thanks a lot!
