### ISSUE TITLE
What does inc1-inc4 represent in provided pretrained models?

### ISSUE THREAD

**Issue by wyf0912** [Vandermode/ELD#31]
Thanks for sharing the pre-trained model.
May I know what inc1-inc4 represents?

![image](https://user-images.githubusercontent.com/26561397/208614061-59a73452-ecee-434e-8d54-6beaed934d1d.png)
![image](https://user-images.githubusercontent.com/26561397/208614288-3c14c8dd-bb83-4669-8dcb-db2d345dc3ad.png)

**Comment by Vandermode** [comment]
Hi, they are just camera ids corresponding to `['CanonEOS70D', 'CanonEOS700D', 'NikonD850', 'SonyA7S2']`. See `noise.py` for more details.

**Comment by wyf0912** [comment]
Got it! Thanks a lot for your quick reply!
