### ISSUE TITLE
Cannot obtian similar results for CanonEOS700D with "P+g" noise model

### ISSUE THREAD

**Issue by wyf0912** [Vandermode/ELD#32]
Thanks again for your great work~

I try to reproduce the results from the baseline model "G+p" in Table 1. 
I can reproduce most of the results. However, for the CanonEOS700D device, the results I obtained are as follows,
```
# *100
PSNR: 39.8162 | SSIM: 0.8780 

# *300
PSNR: 37.6161 | SSIM: 0.8580
```
which is slightly lower than the results in the table
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/26561397/222492665-3366f968-7e3f-418b-a235-38582b5a26ea.png">

Is this a normal discrepancy or, maybe I guess there is a mismatch of the released camera parameter?

**Comment by Vandermode** [comment]
Hi, the results on Canon cameras have some random variations within +-0.3 dB, depending on the camera parameters used. Generally, it's a normal discrepancy, though you might be able to reproduce the results with other random seed or a mixture of camera parameters

**Comment by wyf0912** [comment]
Thanks for your prompt reply!
