### ISSUE TITLE
results are different between the cvpr and tpami versions. 

### ISSUE THREAD

**Issue by cchen156** [Vandermode/ELD#44]
Hi Kaixuan, Table 1 in the CVPR version and Table 2 in the TPAMI version are very different. What caused the difference? @Vandermode

**Comment by Vandermode** [comment]
Hi, thanks for your interest. In the CVPR version, we only evaluate on the indoor scenes from the SID dataset [SID_Sony_15_paired.txt](https://github.com/Vandermode/ELD/blob/master/SID_Sony_15_paired.txt), but in the TPAMI version, we evaluate on the whole dataset [SID_Sony_paired.txt](https://github.com/Vandermode/ELD/blob/master/SID_Sony_paired.txt). Besides, the noise model (and calibration) on PAMI version was further refined with improved performance compared to CVPR version.

Specifically, you can find the following statement in the CVPR version which is not appeared in the PAMI version:

> For quantitative evaluation, we focus on indoor scenes illuminated by natural lights, to avoid flickering effect of alternating current lights
