### ISSUE TITLE
ELD dataset description

### ISSUE THREAD

**Issue by oneTaken** [Vandermode/ELD#6]
Hi,   

I download your pretrained model and ELD dataset to know more details of your paper.  

But I failed with run `test_ELD.sh`  

I found in the ELD dataset, every scene in a specific camera there is 16 raw data and some have 16 corresponding RGB data.  

Is this should be 3 (isos) * 2(lowlight ratio) = 6 examples?  

And I find  `img_ids_set = [[4, 9, 14], [5, 10, 15]]`   in the `the_ELD.py`  adn `gt_ids = np.array([1, 6, 11, 16])` in `sid_dataset.py`.

I do not know exactly what this ids means.

**Comment by Vandermode** [comment]
Thank you for the feedback.
Did you address the problem?

If not, I'll check it later

**Comment by oneTaken** [comment]
Diving into your code and paper more deeply, I find the understanding about the eld dataset.   
In some words, every scene has 16 raw data, and `[4 9 14]-th` case is the scaled `100` lowlight data. and `[5, 10, 15]-th` is the scaled `200` lowlight data.    
 the corredponding gt has 4 case, I do not exactly get the idea of the gt case process.

```
gt_ids = np.array([1, 6, 11, 16])  
 ind = np.argmin(np.abs(self.img_ids[img_id] - gt_ids))  
```

With the noise existance, I do not know use l1 to find gt is a proper way.

**Comment by Vandermode** [comment]
Yes, thanks for the description.

For each scene, I capture the long-exposure reference images four times to avoid accidential error (e.g. scene/camera motion)

This can be examined by calculating the PSNR using image id 1 and 16 (the resulting value should be high enough to ensure no error occurs.

For evaluation, I choose the nearest reference image id w.r.t. the input image id as ground truth, but you are free to use fixed id (e.g. image id 1) as ground truth as well

**Comment by oneTaken** [comment]
In other words, if one gt has very low psnr, this may have some motion. 
By the way, I notice your description in your paper, I think you rexclude the accidential data in the ELD dataset.    
I got it , thanks so much.

**Comment by oneTaken** [comment]
Another question about noisy samples generation.   
I notice the function `generate_noisy_obs` in `sid_dataset.py` which is never be used.  

Is this the noise model parameters?

```
def generate_noisy_obs(y):
    def sample_params():
        # log_a = np.random.uniform(low=np.log(1e-4), high=np.log(1.2e-3))
        log_a = np.random.uniform(low=np.log(1e-4), high=np.log(0.012))
        log_b = np.random.standard_normal() * 0.26 + 2.18 * log_a
        log_c = np.random.uniform(low=np.log(1e-9), high=np.log(1e-7))
        log_d = np.random.uniform(low=np.log(1e-8), high=np.log(1e-6))
        a = np.exp(log_a)
        b = np.exp(log_b)
        c = np.exp(log_c)
        d = np.exp(log_d)
        return a, b, c, d
    
    # sig_read = 10. ** np.random.uniform(low=-3., high=-1.5)
    # sig_shot = 10. ** np.random.uniform(low=-2., high=-1.)
    
    ratio = np.random.uniform(low=100, high=300)
    # ratio = 1
    
    a, b, c, d = sample_params()
    chi = 1 / a
    q = 1 / (2**14)
    
    y = y / ratio

    # Burst denoising
    # shot = np.random.randn(*y.shape).astype(np.float32) * np.sqrt(np.maximum(y, 1e-10)) * sig_shot
    # read = np.random.randn(*y.shape).astype(np.float32) * sig_read
    # z = y + shot + read
    
    if a > 1.2e-3:
        z = np.random.poisson(chi*y).astype(np.float32) / chi
    else:
        z = y + np.random.randn(*y.shape).astype(np.float32) * np.sqrt(np.maximum(y*a, 1e-10))
    
    z = z + np.random.randn(*y.shape).astype(np.float32) * np.sqrt(np.maximum(b, 1e-10)) # Gaussian noise
    z = z + np.random.randn(1, y.shape[1], 1).astype(np.float32) * np.sqrt(c) # banding noise
    z = z + np.random.uniform(low=-0.5*q, high=0.5*q) # quantisation error

    z = z * ratio

    return z
```

**Comment by Vandermode** [comment]
Ok, I just forgot to delete it (as I should have not released it)

It's a preliminary version of the noise model developed during the research stage. 
It's far way from our final model , but may give you some hints to reproduce it
